import Header from '@/components/navbar/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/footer/Footer';

const inter = Inter({
	subsets: ['latin'],
	weight: ['100', '400', '700', '900'],
	variable: '--inter',
});

export const metadata: Metadata = {
	title: 'ddaeunbblog',
	description: 'Generated by ddaeunbb',
	icons: {
		icon: '/favicon.png',
		apple: '/favicon.png',
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="font-sans text-neutral-800 mx-auto max-w-3xl px-6 lg:max-w-6xl lg:px-8">
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
